name: ganama
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  front_matter_ml: ^1.2.0
  path: ^1.8.0
  yaml_writer: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
