name: Publish Ganama Services Application

on:
  push:
    branches:
      - main
    paths:
      - 'applications/ganama-services/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: |
          cd applications/ganama-services
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/ganama-services .

      - name: Publish image to Docker-hub
        run: |
          cd applications/ganama-services
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/ganama-services:latest
