name: Publish Gemini LLM Application

on:
  push:
    branches:
      - main
    paths:
      - 'applications/gemini-llm/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: |
          cd applications/gemini-llm
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/gemini-llm .

      - name: Publish image to Docker-hub
        run: |
          cd applications/gemini-llm
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/gemini-llm:latest
